// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeResp.proto

package com.book.proto;

public interface SubscribeRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.book.proto.SubscribeResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 subReqID = 1;</code>
   */
  boolean hasSubReqID();
  /**
   * <code>required int32 subReqID = 1;</code>
   */
  int getSubReqID();

  /**
   * <code>required int32 resqCode = 2;</code>
   */
  boolean hasResqCode();
  /**
   * <code>required int32 resqCode = 2;</code>
   */
  int getResqCode();

  /**
   * <code>required string desc = 3;</code>
   */
  boolean hasDesc();
  /**
   * <code>required string desc = 3;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>required string desc = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
