// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeReq.proto

package com.book.proto;

public interface SubscribeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.book.proto.SubscribeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 subReqID = 1;</code>
   */
  boolean hasSubReqID();
  /**
   * <code>required int32 subReqID = 1;</code>
   */
  int getSubReqID();

  /**
   * <code>required string userName = 2;</code>
   */
  boolean hasUserName();
  /**
   * <code>required string userName = 2;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>required string userName = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>required string productName = 3;</code>
   */
  boolean hasProductName();
  /**
   * <code>required string productName = 3;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>required string productName = 3;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>required string address = 4;</code>
   */
  boolean hasAddress();
  /**
   * <code>required string address = 4;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>required string address = 4;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
