// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.gwz.proto;

public interface MyResponesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gwz.proto.MyRespones)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 1;</code>
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
