// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.gwz.proto;

public interface StreamResponesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gwz.proto.StreamRespones)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string respones_info = 1;</code>
   */
  java.lang.String getResponesInfo();
  /**
   * <code>string respones_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponesInfoBytes();
}
