// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.gwz.proto;

/**
 * Protobuf type {@code com.gwz.proto.StudentResponesList}
 */
public  final class StudentResponesList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gwz.proto.StudentResponesList)
    StudentResponesListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StudentResponesList.newBuilder() to construct.
  private StudentResponesList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StudentResponesList() {
    studentRespones_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StudentResponesList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              studentRespones_ = new java.util.ArrayList<com.gwz.proto.StudentRespones>();
              mutable_bitField0_ |= 0x00000001;
            }
            studentRespones_.add(
                input.readMessage(com.gwz.proto.StudentRespones.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        studentRespones_ = java.util.Collections.unmodifiableList(studentRespones_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gwz.proto.StudentProto.internal_static_com_gwz_proto_StudentResponesList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gwz.proto.StudentProto.internal_static_com_gwz_proto_StudentResponesList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gwz.proto.StudentResponesList.class, com.gwz.proto.StudentResponesList.Builder.class);
  }

  public static final int STUDENTRESPONES_FIELD_NUMBER = 1;
  private java.util.List<com.gwz.proto.StudentRespones> studentRespones_;
  /**
   * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
   */
  public java.util.List<com.gwz.proto.StudentRespones> getStudentResponesList() {
    return studentRespones_;
  }
  /**
   * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
   */
  public java.util.List<? extends com.gwz.proto.StudentResponesOrBuilder> 
      getStudentResponesOrBuilderList() {
    return studentRespones_;
  }
  /**
   * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
   */
  public int getStudentResponesCount() {
    return studentRespones_.size();
  }
  /**
   * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
   */
  public com.gwz.proto.StudentRespones getStudentRespones(int index) {
    return studentRespones_.get(index);
  }
  /**
   * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
   */
  public com.gwz.proto.StudentResponesOrBuilder getStudentResponesOrBuilder(
      int index) {
    return studentRespones_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < studentRespones_.size(); i++) {
      output.writeMessage(1, studentRespones_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < studentRespones_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, studentRespones_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gwz.proto.StudentResponesList)) {
      return super.equals(obj);
    }
    com.gwz.proto.StudentResponesList other = (com.gwz.proto.StudentResponesList) obj;

    boolean result = true;
    result = result && getStudentResponesList()
        .equals(other.getStudentResponesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStudentResponesCount() > 0) {
      hash = (37 * hash) + STUDENTRESPONES_FIELD_NUMBER;
      hash = (53 * hash) + getStudentResponesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gwz.proto.StudentResponesList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gwz.proto.StudentResponesList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gwz.proto.StudentResponesList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gwz.proto.StudentResponesList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gwz.proto.StudentResponesList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gwz.proto.StudentResponesList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gwz.proto.StudentResponesList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gwz.proto.StudentResponesList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gwz.proto.StudentResponesList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gwz.proto.StudentResponesList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gwz.proto.StudentResponesList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gwz.proto.StudentResponesList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gwz.proto.StudentResponesList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gwz.proto.StudentResponesList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gwz.proto.StudentResponesList)
      com.gwz.proto.StudentResponesListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gwz.proto.StudentProto.internal_static_com_gwz_proto_StudentResponesList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gwz.proto.StudentProto.internal_static_com_gwz_proto_StudentResponesList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gwz.proto.StudentResponesList.class, com.gwz.proto.StudentResponesList.Builder.class);
    }

    // Construct using com.gwz.proto.StudentResponesList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStudentResponesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (studentResponesBuilder_ == null) {
        studentRespones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        studentResponesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gwz.proto.StudentProto.internal_static_com_gwz_proto_StudentResponesList_descriptor;
    }

    public com.gwz.proto.StudentResponesList getDefaultInstanceForType() {
      return com.gwz.proto.StudentResponesList.getDefaultInstance();
    }

    public com.gwz.proto.StudentResponesList build() {
      com.gwz.proto.StudentResponesList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.gwz.proto.StudentResponesList buildPartial() {
      com.gwz.proto.StudentResponesList result = new com.gwz.proto.StudentResponesList(this);
      int from_bitField0_ = bitField0_;
      if (studentResponesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          studentRespones_ = java.util.Collections.unmodifiableList(studentRespones_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.studentRespones_ = studentRespones_;
      } else {
        result.studentRespones_ = studentResponesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gwz.proto.StudentResponesList) {
        return mergeFrom((com.gwz.proto.StudentResponesList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gwz.proto.StudentResponesList other) {
      if (other == com.gwz.proto.StudentResponesList.getDefaultInstance()) return this;
      if (studentResponesBuilder_ == null) {
        if (!other.studentRespones_.isEmpty()) {
          if (studentRespones_.isEmpty()) {
            studentRespones_ = other.studentRespones_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStudentResponesIsMutable();
            studentRespones_.addAll(other.studentRespones_);
          }
          onChanged();
        }
      } else {
        if (!other.studentRespones_.isEmpty()) {
          if (studentResponesBuilder_.isEmpty()) {
            studentResponesBuilder_.dispose();
            studentResponesBuilder_ = null;
            studentRespones_ = other.studentRespones_;
            bitField0_ = (bitField0_ & ~0x00000001);
            studentResponesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentResponesFieldBuilder() : null;
          } else {
            studentResponesBuilder_.addAllMessages(other.studentRespones_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gwz.proto.StudentResponesList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gwz.proto.StudentResponesList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.gwz.proto.StudentRespones> studentRespones_ =
      java.util.Collections.emptyList();
    private void ensureStudentResponesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        studentRespones_ = new java.util.ArrayList<com.gwz.proto.StudentRespones>(studentRespones_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gwz.proto.StudentRespones, com.gwz.proto.StudentRespones.Builder, com.gwz.proto.StudentResponesOrBuilder> studentResponesBuilder_;

    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public java.util.List<com.gwz.proto.StudentRespones> getStudentResponesList() {
      if (studentResponesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(studentRespones_);
      } else {
        return studentResponesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public int getStudentResponesCount() {
      if (studentResponesBuilder_ == null) {
        return studentRespones_.size();
      } else {
        return studentResponesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public com.gwz.proto.StudentRespones getStudentRespones(int index) {
      if (studentResponesBuilder_ == null) {
        return studentRespones_.get(index);
      } else {
        return studentResponesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public Builder setStudentRespones(
        int index, com.gwz.proto.StudentRespones value) {
      if (studentResponesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentResponesIsMutable();
        studentRespones_.set(index, value);
        onChanged();
      } else {
        studentResponesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public Builder setStudentRespones(
        int index, com.gwz.proto.StudentRespones.Builder builderForValue) {
      if (studentResponesBuilder_ == null) {
        ensureStudentResponesIsMutable();
        studentRespones_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentResponesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public Builder addStudentRespones(com.gwz.proto.StudentRespones value) {
      if (studentResponesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentResponesIsMutable();
        studentRespones_.add(value);
        onChanged();
      } else {
        studentResponesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public Builder addStudentRespones(
        int index, com.gwz.proto.StudentRespones value) {
      if (studentResponesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentResponesIsMutable();
        studentRespones_.add(index, value);
        onChanged();
      } else {
        studentResponesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public Builder addStudentRespones(
        com.gwz.proto.StudentRespones.Builder builderForValue) {
      if (studentResponesBuilder_ == null) {
        ensureStudentResponesIsMutable();
        studentRespones_.add(builderForValue.build());
        onChanged();
      } else {
        studentResponesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public Builder addStudentRespones(
        int index, com.gwz.proto.StudentRespones.Builder builderForValue) {
      if (studentResponesBuilder_ == null) {
        ensureStudentResponesIsMutable();
        studentRespones_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentResponesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public Builder addAllStudentRespones(
        java.lang.Iterable<? extends com.gwz.proto.StudentRespones> values) {
      if (studentResponesBuilder_ == null) {
        ensureStudentResponesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, studentRespones_);
        onChanged();
      } else {
        studentResponesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public Builder clearStudentRespones() {
      if (studentResponesBuilder_ == null) {
        studentRespones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        studentResponesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public Builder removeStudentRespones(int index) {
      if (studentResponesBuilder_ == null) {
        ensureStudentResponesIsMutable();
        studentRespones_.remove(index);
        onChanged();
      } else {
        studentResponesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public com.gwz.proto.StudentRespones.Builder getStudentResponesBuilder(
        int index) {
      return getStudentResponesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public com.gwz.proto.StudentResponesOrBuilder getStudentResponesOrBuilder(
        int index) {
      if (studentResponesBuilder_ == null) {
        return studentRespones_.get(index);  } else {
        return studentResponesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public java.util.List<? extends com.gwz.proto.StudentResponesOrBuilder> 
         getStudentResponesOrBuilderList() {
      if (studentResponesBuilder_ != null) {
        return studentResponesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(studentRespones_);
      }
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public com.gwz.proto.StudentRespones.Builder addStudentResponesBuilder() {
      return getStudentResponesFieldBuilder().addBuilder(
          com.gwz.proto.StudentRespones.getDefaultInstance());
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public com.gwz.proto.StudentRespones.Builder addStudentResponesBuilder(
        int index) {
      return getStudentResponesFieldBuilder().addBuilder(
          index, com.gwz.proto.StudentRespones.getDefaultInstance());
    }
    /**
     * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
     */
    public java.util.List<com.gwz.proto.StudentRespones.Builder> 
         getStudentResponesBuilderList() {
      return getStudentResponesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gwz.proto.StudentRespones, com.gwz.proto.StudentRespones.Builder, com.gwz.proto.StudentResponesOrBuilder> 
        getStudentResponesFieldBuilder() {
      if (studentResponesBuilder_ == null) {
        studentResponesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.gwz.proto.StudentRespones, com.gwz.proto.StudentRespones.Builder, com.gwz.proto.StudentResponesOrBuilder>(
                studentRespones_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        studentRespones_ = null;
      }
      return studentResponesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.gwz.proto.StudentResponesList)
  }

  // @@protoc_insertion_point(class_scope:com.gwz.proto.StudentResponesList)
  private static final com.gwz.proto.StudentResponesList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gwz.proto.StudentResponesList();
  }

  public static com.gwz.proto.StudentResponesList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StudentResponesList>
      PARSER = new com.google.protobuf.AbstractParser<StudentResponesList>() {
    public StudentResponesList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StudentResponesList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StudentResponesList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StudentResponesList> getParserForType() {
    return PARSER;
  }

  public com.gwz.proto.StudentResponesList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

