// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.gwz.proto;

public interface StudentResponesListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gwz.proto.StudentResponesList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
   */
  java.util.List<com.gwz.proto.StudentRespones> 
      getStudentResponesList();
  /**
   * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
   */
  com.gwz.proto.StudentRespones getStudentRespones(int index);
  /**
   * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
   */
  int getStudentResponesCount();
  /**
   * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
   */
  java.util.List<? extends com.gwz.proto.StudentResponesOrBuilder> 
      getStudentResponesOrBuilderList();
  /**
   * <code>repeated .com.gwz.proto.StudentRespones studentRespones = 1;</code>
   */
  com.gwz.proto.StudentResponesOrBuilder getStudentResponesOrBuilder(
      int index);
}
